### PR TITLE
Annual loan payment: comprehensive option trigger

### PR DESCRIPTION
**Pull request by zijistark**
- The annual loan payment event has always had an ultra-simplified,
  best-case option trigger for "pay back as much as we can."  I've
  replaced the trigger with a comprehensive, exact minimum wealth
  requirement (not including stewardship bonuses) for all possible loan
  combinations using the best available minimum repayment strategy for
  each.
- This will properly make the option disabled for the AI and player
  when, in practice, it would do nothing different than the first option
  (minimum interest payment).  For the player, this is just more correct
  and helpful, especially since the player does not get to see what
  actually gets paid without manually inspecting their debts afterward.
- This enables more creative repayment strategies or other event options
  to be added to the event in the future.  It also provides the foundation
  for a "Pay back as much as possible." loan decision to eventually
  replace the clutter of now-more-complex tiers of "Pay back X-sized
  loan." decisions.

### CODE REVIEW

**Comment by Meneth** [comment]
That looks like a very inefficient trigger.
Besides, it isn't like it being available when it won't quite do anything really is much of an issue.

**Comment by zijistark** [comment]
Inefficient?  Like, in terms of CPU cycles?  As inefficiently as I'm sure,

```
has_character_modifier = <integer index into a char object bitmap>
```

is probably implemented by Paradox, I assert >99% of the performance profile of the event, due to actual mutation of modifiers and values (write locks required) in the effects and the overhead of simply being an event (messaging system, polling, queuing, locking, and dispatch overhead), does not include a single cycle spent on that trigger.  I mean, it's important to keep things in perspective.

Or are you saying that the logic is expressed in a verbose manner (inefficient in that way)?  I can understand that objection.  I would agree with you if a) it weren't already written, b) I hadn't planned on using the exact same base logic (expanded slightly in script verbiage with some hidden_tooltip thrown-in) for a decision's allow trigger (and the base for a tooltip-readable effect, if I felt ambitious).  I explained this in the commit notes and the PR notes (see the note at the end).

For the decision, the precision is absolutely required, so if I go ahead with the decision[1], either a form of that logic gets reused or some very tedious alternative could be used that reduced the number of calls to `has_character_modifier` but was, to say the least, scary and less maintainable.  The fact that I could reuse that logic template as a base for the allow and potentially part of the effect tooltip was just a bonus (though, if I were to proceed, I now think that I'd take a different approach with the effect's tooltip, as that logic is significantly more complex if it's properly polished with custom_tooltips).

I can reduce the number of calls to `has_character_modifier` significantly, but the result would be tediously error-prone (I think-- I haven't actually tried doing it).  Since I did not see performance to reasonably be of any concern where this trigger was applied (and firmly do not believe the performance of the trigger itself would actually measurably differ from an alternate implementation, especially given the frequency of evaluation the trigger will ever see, even in aggregate), doing it the most maintainable and quick-to-read way just seemed right. [Totally flattened Sorted + Simply every permutation of binary digits in a 4-bit number sans 0000, which is inherently encoded with a fundamental sort order and payment strategy selection, by virtue of the fact that the loans increase exactly two-fold with each added tier, just as a binary representation of an integer does and alternate between even and odd as adjacent loan-taken slots toggle on and off.]

[1]However, if you have a problem with that trigger being in that far-off, distant event, then I'd guess that you may block me from adding a one-click decision to auto-pay the max. possible?  I thought that would be a killer decision to reduce clutter by eliminating all the tiered repayment decisions[2].  I probably would've had it done it by now actually, which could be disappointing...

[2]The only reason not to eliminate them all once you had auto-pay-max in place would be so that players could pay-back exactly the chunks they wanted (less than max).  Thing is, they can safely auto-pay the max possible on their first click, which will be all they want in 95% of cases, and for the other 5% that wanted to pay back less, they have the option of immediately reusing a now-freed loan slot on their second click.  Anyway, even if you didn't want to get rid of the myriad repayment tiers that are now polluting the menu with a one-click option, I'd figured the one-click option was still very worthwhile-- it'd just be the sane solution at the bottom of the loans menu.]

I will wait to hear if your gripe was with the verbosity/style or actually with CPU efficiency.

I'm assuming you meant the verbosity/style for now.  And assuming that you didn't read the full PR note and thus didn't understand that it was just a fitting puzzle piece for the trigger that was also to be reused in something else that was more important and demanded a perfect fit.

I must say, if code elegance is your optimization target, then you are simply looking for it in the wrong place, my friend.  For that, we look to C++ or Python or sometimes even Java (unless we're academics).  With CK2/Paradox modding, you know as well as I that there's a good chance that you'll be stuck with a square peg and a round hole for any given nontrivial task.

**Comment by Meneth** [comment]
Essentially, when at all possible I prefer to keep triggers simple. In this case I can't say I really say I quite see the benefit the trigger brings. Sure, it'll hide the button when one can't actually repay any loans, but it isn't as if having the button there causes any real issues.

**Comment by zijistark** [comment]
OK, so it's not about efficiency.  Good.  That was not really going to lead to a useful resolution.

Style.  You've not commented on any of the other text I jammed-out, so I'll stick to that.

Yeah, so as I said, what if the trigger did need to be exactly precise for something else?  What if that something else was related and the trigger was the correct answer to both questions?  Wouldn't it be a maintainability boost to use the cookie-cutter trigger template then?

Also, if efficiency isn't the concern and the thing does precisely solve the problem for which it is posed and it's already written and tested and does provide less confusing behavior _and_ it's nothing but a trigger, what's the harm in it adding the slight amount of extra value that it does as is?  If the payment strategies or loan tiers or loan amounts change in the future, the trigger can either be easily modified or it can be wiped altogether as it essentially was previously.

I mean, I don't want to waste another word over this specific trigger.  It was nifty, it was fast to code, and it was a template for code that I was planning to write that actually did require the precision, but anymore words on my part regarding its usage in meneth.203.b are wasted, as you're right, it really doesn't matter all that much on its own.  If you hate the thing and it must go, then I'll remove it.  [In fact, I think I hate the thing too now by association.]  Do keep this PR open for now, though.  The unread comments contain useful information for what I'd like to [try] pushing to you next, though I might get some sleep first.

**Comment by zijistark** [comment]
You know what? Scratch all of that.  I think that I'm being too damn principled in response to you doing the same, frankly, even though I think we basically hold the same positions.

Closing this PR.

More important:

HIP is releasing this evening. Is PB 3.4.1 going to be included? If so, when will you merge beta into master today?  I'd like to get one more change in, and it's not this one, obviously.  I would also like to sleep, however, and since it's already early afternoon for you...  It'll depend on the answer to those questions, I guess.

**Comment by Meneth** [comment]
I plan to release HIP at 2000 CET. Due to build and upload times, to be on the safe side I want everything finalized by 1930 CET.
So if you pull request before then, and it is obviously a good change, it should be in the first release.

**Pull request closed without merging**
