### PR TITLE
Additional CTA chance balancing, new ambition icon

### PR DESCRIPTION
**Pull request by zijistark**
- Professional-looking CTA ambition icon from AnaxXiphos to supercede my placeholder icon.
- Rolled-back CTA combat impulse chance base weight reduction to -20% rather than -40%.
- Partially countervailing the higher chance for players is a new flat bonus of 33% to the random weight given to all AI characters with a CTA ambition selected.
- A few more fine-grained tiers of martial attribute correlation were also added, FWIW, but the rest is mostly comment block clarification/cleanup.

It looks like this is the right branch to initiate a pull request to at the moment, as you've integrated everything, and this should make it into 3.4.1, and for whatever reason, the diff against your beta is currently re-implementing your payment-by-half commit.

### CODE REVIEW

**Comment by zijistark** [comment]
I should note that your payment-by-half commit _is_ included here on Meneth/master, hence the lack of its reimplementation in this cleanly rebased pull request.

**Comment by Meneth** [comment]
You're merging to the wrong branch.

**Comment by Meneth** [comment]
My last merge was something like 20 commits ago. The beta branch is still the correct branch to merge to.

**Comment by zijistark** [comment]
Indeed, you're right.  It seems I have a commit in my repository (repay
half by event) that you authored that is more recent than your own repo's
present version in its beta branch.  I suspect you may have reverted it in
beta through a merge and now I'm bringing it back in.

-m

**Pull request closed without merging**
