### PR TITLE
Fixed Bohemia being de jure vassal to HRE in 769

### PR DESCRIPTION
**Pull request by zijistark**
Fairly sure the HRE didn't exist in 769. ;)

### CODE REVIEW

**Comment by Meneth** [comment]
It does in PB right now. Though I plan on changing that. But right now, it being dejure HRE is WAD.

**Comment by zijistark** [comment]
K, I'll just override this in EMF then.

**Comment by Meneth** [comment]
Sounds good.
I think what I'll end up doing is have Germania be dejure until the HRE is formed, and then merge the vanilla and PB HRE formation decisions in some way. Hope to look into that sometime this week.

**Comment by zijistark** [comment]
Yes, that's more or less what I've done in EMF.

Except the vanilla HRE formation decisions are still a bit rough around the edges when using SWMH, and the regular vanilla HRE formation decision (not `form_the_hre_early`, which is awesome) needs some love (mostly to make it more difficult to form).

I have no `e_hre_french` ATM.  The vanilla Empire of Francia is already a superset of the de jure kingdom titles that `e_hre_french` covers. The only difference is that it's not called Saint-Empire Romain and is harder to form than `e_hre_french`.  I might be just fine with that for now, frankly, esp. since it will just become HRE de jure if `form_the_hre_early` is taken (albeit, it'll be white-colored rather than something blue, although it'll retain the Frankish CoA).

**Comment by Meneth** [comment]
I'll probably keep the French HRE, since I think it is pretty neat.

**Pull request closed without merging**
