### PR TITLE
Removed Frisian culture

### PR DESCRIPTION
**Pull request by cybrxkhan**
We done got dem Frisian folk in vanilla

### CODE REVIEW

**Comment by zijistark** [comment]
Was the intention to also update all the norsegael namelists? It appears that they've been converted to UTF-8.

**Comment by Meneth** [comment]
Those have gone back and forth a number of times, I believe. Don't think it should cause any issues.

**Comment by zijistark** [comment]
UTF-8 in the culture files is a classic source of errors, not the least of which is simply names appearing with random symbols in them.

**Comment by Meneth** [comment]
Hmmf. That's not great then.

**Comment by zijistark** [comment]
Is this elsewhere? If not, I suppose a simple revert and then re-deletion of frisian culture w/o touching anything else would do it.

**Comment by Meneth** [comment]
That would do it, yeah.

**Comment by zijistark** [comment]
Meneth, all you need to do is click 'Revert Pull Request,' and then delete west_germanic from PB_cultures.txt.  I've got to go revert a PR by hand among other things... _ahem_

**Comment by Meneth** [comment]
I know I know. Just a bit lazy. Done now tho.

**Comment by zijistark** [comment]
:+1:

**Comment by cybrxkhan** [comment]
The UTF-8 may've been my fault, sorry about that :\

**Comment by zijistark** [comment]
Oh, it **was** your fault, and this is your third UTF-8 strike. You know what that means in Texas? [ Is California one of them extradition countries? :dash: ]

**Pull request merged**
